docs: Update README.md since the chain specification CLI value is variable depending on the Polkadot version installed
After installing the very latest version of Polkadot with `cargo install --git https://github.com/paritytech/polkadot.git polkadot`, I followed the instructions under the [PoC-1 Testnet](https://github.com/paritytech/polkadot#poc-1-testnet) of running `polkadot --chain=poc-1` to connect to the global PoC-1 Testnet, however it returned the following error since the latest version doesn't appear to support the `poc-1` CLI option value anymore. 

```bash
$ polkadot --chain=poc-1
thread 'main' panicked at 'Invalid chain name: poc-1', polkadot/cli/src/lib.rs:151:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I found that other chain specifications were available including dev, local or poc-2 when I ran `polkadot --help`.
I was able to run PoC-2 Testnet when I ran `polkadot --chain=poc-2`

Propose to refer to the chain specification with `CHAIN_SPEC` instead of `poc-1` to encourage the user to use the Polkadot CLI help menu to view the available values depending on the version of Polkadot that they installed